### PR TITLE
build_sphinx doesn't work on Python 3

### PR DESCRIPTION
**Pull request by cdeil**
For me this doesn't work with Python 3.4 and Astropy master:
```
$ python setup.py build_sphinx
...
  File "/Users/deil/code/photutils/astropy_helpers/astropy_helpers/sphinx/ext/automodsumm.py", line 203, in run
    self.arguments = [' '.join(clsnms).decode('utf-8')]
AttributeError: 'str' object has no attribute 'decode'
```
(see full traceback [here](https://gist.github.com/cdeil/99c717f807e0017246a9#file-gistfile1-txt-L83).)

Can someone confirm this issue?
I'll try running the sphinx build with Python 3 on travis-ci and then update the `astropy-helpers` pointer to the latest 0.4.4 release (see [astropy-helpers on pypi](https://pypi.python.org/pypi/astropy-helpers/)) to see if that is the issue.

### CODE REVIEW

**Comment by astrofrog** [comment]
I *think* this is fixed in the latest version of the helpers.

**Comment by cdeil** [comment]
Travis-ci shows one unrelated issue: #237

And then it shows the same Sphinx error on Python 3 I see locally:
https://travis-ci.org/astropy/photutils/jobs/47222672#L2072

So I'll try the astropy-helpers update now.

**Comment by astrofrog** [comment]
@cdeil - looks like it works better - now it's failing because there are five warnings in the docs build in Python 3.

**Comment by cdeil** [comment]
Does someone know how to get rid of these Sphinx warning on Python 3?
```
photutils.Aperture.rst:7: WARNING: py:class reference target not found: 
photutils.Background.rst:7: WARNING: py:class reference target not found:
photutils.SegmentProperties.rst:7: WARNING: py:class reference target not found:
photutils.background.Background.rst:7: WARNING: py:class reference target not found: 
photutils.segmentation.SegmentProperties.rst:7: WARNING: py:class reference target not found: builtins.object
```

**Comment by cdeil** [comment]
There's also this!?
```
Running Sphinx v1.2.3
loading pickled environment... failed: [Errno 2] No such file or directory: '/Users/deil/code/photutils/docs/_build/doctrees/environment.pickle'
```

**Comment by astrofrog** [comment]
Ignore the pickle warning, I think that always occurs for a new build?

@bsipocz might have ideas about the warnings.

**Comment by cdeil** [comment]
> Ignore the pickle warning, I think that always occurs for a new build?

I think so too ... but can we get rid of it?
Is this an `astropy` or `astropy-helpers` problem and is there a GH issue about it?

**Comment by astrofrog** [comment]
@cdeil - if anything, it's a sphinx issue. Create a new sphinx docs directory with ``sphinx-quickstart`` then do ``make html`` and you will see the same error.

**Comment by cdeil** [comment]
@astrofrog - You're right about the pickle message ... I've filed an issue with Sphinx to make it more clear that this is normal: https://github.com/sphinx-doc/sphinx/issues/1680

**Comment by larrybradley** [comment]
Locally, I'm seeing those same five `Sphinx` warnings with python 3.4 and astropy (both master and stable) after upgrading `astropy-helpers`.  I have no idea how to fix them.

**Comment by cdeil** [comment]
Looks related: #152

**Comment by bsipocz** [comment]
@cdeil - I'm checking this now.

**Comment by bsipocz** [comment]
I'll try to fix this tomorrow with the blind approach, as a whole new set of errors are coming from the python3.4 and python3.3 installs I have access to (but those errors are most probably unrelated, and are only due to improper setup).

**Comment by cdeil** [comment]
@bsipocz - Thanks!

If you're haven't tried it, with Miniconda you can get Python 2 / 3 development environments on any machine within a few minutes (see e.g. commands [here](https://gammapy.readthedocs.org/en/latest/install.html#install-gammapy-and-its-dependencies-using-conda)) ... it's really nice.

**Comment by bsipocz** [comment]
For some unknown reason, the ``object`` class is referenced as ``builtins.object`` rather than just ``object`` when ``build_sphinx`` is run with python3. And also for some unknown reason this is missing from the official python3 ``objects.inv``. Updating our local inventory solves the broken links (https://github.com/astropy/astropy-helpers/pull/123), however we may need to wait for a new helpers release to include in in photutils.

**Comment by cdeil** [comment]
I've removed the `-w` on the Python 3 Sphinx build on travis-ci for now ... easiest to add it once https://github.com/astropy/astropy-helpers/pull/123 has made it into a stable astropy-helpers release.
