### ISSUE TITLE
Background2D depends on unreleased scipy version 1.8.0

### ISSUE THREAD

**Issue by stewi2** [astropy/photutils#1287]
With photutils 1.3.0, I get the following exception when I call `Background2D.background()`:

```python
/usr/local/lib/python3.7/dist-packages/photutils/background/interpolators.py in __call__(self, mesh, bkg2d_obj)
     82             zoom_factor = bkg2d_obj.box_size
     83             result = zoom(mesh, zoom_factor, order=self.order, mode=self.mode,
---> 84                           cval=self.cval, grid_mode=self.grid_mode)
     85             return result[0:bkg2d_obj.data.shape[0],
     86                           0:bkg2d_obj.data.shape[1]]

TypeError: zoom() got an unexpected keyword argument 'grid_mode'
```

That `grid_mode` parameter was added to scipy in [this commit ](https://github.com/scipy/scipy/commit/d45c5f7f5967f5e5f69e29c9e4124b7a10f1a221), which is tagged with `v1.8.0rc3`, so a release candidate that has not been released yet (although it was implemented over a year ago).

**Comment by larrybradley** [comment]
@stewi2 What version of `scipy` are you using?  `grid_mode` was added in to `scipy.ndimage.zoom` in `scipy 1.6.0` (https://docs.scipy.org/doc/scipy/release.1.6.0.html?highlight=grid_mode), which is the minimum required version for `photutils` (https://github.com/astropy/photutils/blob/main/setup.cfg#L35).  Our CI tests are running fine.  Can you double check your `scipy` version?

**Comment by larrybradley** [comment]
More background on the addition of `grid_mode` in `scipy 1.6.0`:  https://labs.quansight.org/blog/2021/01/scipy-ndimage-interpolation/

**Comment by stewi2** [comment]
@larrybradley Looks like I was using scipy 1.4.1 (default in Colab). I could have sworn I had updated to 1.7.3 and got the same error, but maybe the notebook kernel didn't reload properly afterwards. Either way, it now works with photutils 1.3.0 and scipy 1.6.0 installed explicitly.  Strange that when I simply installed photutils via `pip install photutils` it didn't also upgrade scipy as a dependency:

![image](https://user-images.githubusercontent.com/986590/150921702-fbba110b-c528-411c-867e-e38a5ad7700a.png)

I'm not all too familiar with setuptools, but install_requires only mentions astropy and numpy, but not scipy? Note that the above output doesn't mention scipy as a dependency at all.

**Comment by larrybradley** [comment]
`numpy` and `astropy` are the only strict requirements.  `scipy` is an optional dependency (https://photutils.readthedocs.io/en/latest/install.html).  If you want to install `photutils` with all of the optional dependencies, use `pip install "photutils[all]"`.
